### ISSUE TITLE
Removing your banner

### ISSUE THREAD

**Issue by panopticdesign** [weDevsOfficial/happy-elementor-addons#1]
How do I remove your banner in my site admin panel? I find it intrusive that you think it is OK to automatically add a banner to my site without my permission and then provide no simple way to remove it.

**Comment by thebengalboy** [comment]
Hello @panopticdesign 

You may be meant the top banner with a 'thank you' message from the Happy Addons team. You can simply close the message and it shouldn't show again if you just close it once. Reference screenshot: https://prnt.sc/oujvfb

Thanks

**Comment by panopticdesign** [comment]
I did NOT install your plugin and the top banner "X" does NOT work and will NOT remove the banner. 

How did you insert this into my site without my permission? How do I kill the ad banner?

**Comment by hasinhayder** [comment]
Hi,

I think there has been some misunderstanding. I don't understand which
banner you're talking about? Could you please share a screenshot?

Thanks

**Comment by thebengalboy** [comment]
Hello @panopticdesign 

We are really sorry for the inconvenience. Actually, it was coming from our another plugin WooCommerce Conversion Tracking. 

However, we have already removed the banner, simply updating the WooCommerce Conversion Tracking Plugin to the latest version will solve the problem.

Thanks
