### ISSUE TITLE
Calendly widget background styling has no effect

### ISSUE THREAD

**Issue by toopixel** [weDevsOfficial/happy-elementor-addons#10]
Whatever we change as background color in the Calendly widget, it has no effet, it doesn't change the background color.
This is happending since last update of HappyAddons on the 11.11.2019 it was working before.

**Comment by obiPlabon** [comment]
@toopixel Thanks for reporting.

Calendly changed the pricing model and made color-changing options PRO only. I'm afraid we have nothing to do here.

Thanks
