### ISSUE TITLE
Justified Grid Gallery 

### ISSUE THREAD

**Issue by kreggjacoby** [weDevsOfficial/happy-elementor-addons#11]
Hi, experiencing a strange issue using the justified grid galley block. On mobile it's rotating my pictures. Using dev tools in chrome it shows the pics correct orientation. Happens on both safari and chrome in iOS.
![IMG_0837](https://user-images.githubusercontent.com/7316315/69388152-42da2e00-0c85-11ea-91d2-63c4e0cebfd1.png)
<img width="677" alt="Screen Shot 2019-11-21 at 5 30 56 PM" src="https://user-images.githubusercontent.com/7316315/69388153-42da2e00-0c85-11ea-9bc3-5fa62a243aeb.png">

**Comment by obiPlabon** [comment]
@kreggjacoby Thanks for reporting.

After getting your report we tested Justified Gallery widget on both Safari and Chrome in iOS (iPhone 6s). But we couldn't recreate the problem. Could you please give us more information? Like your phone model, screen size, zoom level etc.

Thanks

**Comment by kreggjacoby** [comment]
Hi yes I've done some testing myself. Seems like only the X phones in iOS. Works fine in iPhone 6s, iPhone 8, and android s7 I tested. My iPhone X and my friend's iPhone XR both rotates those image.  I don't have access to a Plus/Max screen size to try.

**Comment by kreggjacoby** [comment]
X is 5.8 and XR is 6.1. Tested the link on both safari and chrome running current iOS on both. No zoom.

**Comment by kreggjacoby** [comment]
Also note I've updated the domain to communitybucket.com if you want to check live view

**Comment by kreggjacoby** [comment]
Found somebody with a new 11 max pro (large iPhone) and same thing. So seems to be iPhone 10 and 11 and both phone sizes
![11maxpro](https://user-images.githubusercontent.com/7316315/69588418-bc379080-0fa5-11ea-9897-bb3c4744f61c.png)

**Comment by kreggjacoby** [comment]
Sorry never mind. Some kind of wordpress issue. I can't see the photo rotated in the wordpress frontend but went in with ftp and all the wordpress photo sizes are correct bu the "original" upload is sideways.

**Comment by obiPlabon** [comment]
@kreggjacoby Thanks and surprised to see lots of testing! 😀

So the problem was resolved right?

Thanks and let us know if you have any more query.

**Comment by kreggjacoby** [comment]
Yes resolved by manually download the "original" state photo, rotating and re-upload. Weird that all the auto generated pics were rotated correctly but the originals uploaded wrong. The other phones were using one of the wordpress auto generated images while iPhone x and 11 were using the "original" images in the grid.
