### ISSUE TITLE
Update notice failure

### ISSUE THREAD

**Issue by idigitalpromotion** [weDevsOfficial/happy-elementor-addons#12]
I've been noticing that Wordpress is telling me I have a plugin that needs updated yet when I go to do so there is no update needed on any plugins (OR after updating all that DO require updating, a notice still remains).

I just installed Wordfence on a clone of an important site to test it. Within a few minutes of installing Wordfence it notified me of a needed update of Happy Elementor Addons even though none was noted by the plugin itself. See: https://www.screencast.com/t/ichh518wwe8

Here is the Wordfence notification: https://www.screencast.com/t/HX3xkvgK

**Comment by obiPlabon** [comment]
Fixed
