### ISSUE TITLE
Icons won't resize and Live Copy/Paste not copying exact to my client site

### ISSUE THREAD

**Issue by thewebstylist** [weDevsOfficial/happy-elementor-addons#14]
https://immersive4dmedia.demo.site/icons/
The fonts and icon sizes don't look like they do on your site when I live copy/paste and I can't change their small size. The Icon slider sizing doesn't do anything.  Any reason for this and how can I fix pls? The live copy paste feature of Happy Addons Pro is one of my favs but need it working.  BIG THNKS!

<img width="1446" alt="Screenshot 2019-12-20 at 6 44 58 PM" src="https://user-images.githubusercontent.com/38089872/71303126-340c9700-2369-11ea-9f05-fb8abef50cee.png">

**Comment by sw0rking** [comment]
1.3.0

Release Date – Dec 31, 2019

    New: Promo Box widget
    New: CSS Image Masking (Supported widgets: Card, Info Box, Promo Box, Member, Image, Image Box)
    Update: Cross-Domain Copy Paste UX improved
    Update: Cross-Domain Copy Paste performance improved
    Update: Live Copy Paste UX improved
    Update: Live Copy Paste performance improved
    Update: Context menu items are moved to an upper position
    Fix: Unlimited Section Nesting compatibility issue with Elementor
