### ISSUE TITLE
Unlimited Section Nesting - does not work in elementor

### ISSUE THREAD

**Issue by sw0rking** [weDevsOfficial/happy-elementor-addons#15]
In happyaddons pro ver1.2
Unlimited Section Nesting - does not work in elementor ver. 2.8.0-2.8.2
can not create

**Comment by mattotomato** [comment]
The "insert blank section" is missing on the latest version for, 
- Elementor 2.8.2
- Happy Elementor Addons 2.50
- Happy Elementor Addons Pro 1.2.0

Still working in older version:
- Elementor 2.7.5 
- Happy Elementor Addons 2.2.6, 
- Happy Elementor Addons Pro 1.0.2.

**Comment by sw0rking** [comment]
I know this, works on 2.7.6 elementor
why not fix it?

**Comment by mattotomato** [comment]
Haha, i think you've mistaken. I'm a customer waiting for the developer to solve the same issue too.

**Comment by sw0rking** [comment]
I understood correctly)) they month cannot fix !!! ?
what they sell for crazy money !!

**Comment by categoryx** [comment]
Agree, just bought Pro for that specific feature and find out it doesn't work at all in the latest version of elementor.  Why would you sell a product and at least not flag there are issues before people purchase. Will be refunding if not fixed soon.

**Comment by nayemDevs** [comment]
Actually the last Elementor release causes the problem in Nested Section functionality. HappyAddons team is working hard to fix it as soon as possible. Except the Nesting functionality, all others are working fine with the latest free and paid version.

**Comment by sw0rking** [comment]
> all others are working fine with the latest free and paid version.
presets are not updated dynamically

**Comment by obiPlabon** [comment]
Fixed
