### ISSUE TITLE
Unlimited Section Nesting doesn't work on latest version

### ISSUE THREAD

**Issue by mattotomato** [weDevsOfficial/happy-elementor-addons#16]
The "insert blank section" is missing on the latest version for,

Elementor 2.8.2
Happy Elementor Addons 2.50
Happy Elementor Addons Pro 1.2.0
Still working in older version:

Elementor 2.7.5
Happy Elementor Addons 2.2.6,
Happy Elementor Addons Pro 1.0.2.

**Comment by thebengalboy** [comment]
Hello @mattotomato 

You mean, the section nesting? Yes, Section Nesting is not working at this moment after Elementor changed the internal structure and API. Our development team is working hard to get it working soon :)

Thanks

**Comment by sw0rking** [comment]
1.3.0

Release Date – Dec 31, 2019

    New: Promo Box widget
    New: CSS Image Masking (Supported widgets: Card, Info Box, Promo Box, Member, Image, Image Box)
    Update: Cross-Domain Copy Paste UX improved
    Update: Cross-Domain Copy Paste performance improved
    Update: Live Copy Paste UX improved
    Update: Live Copy Paste performance improved
    Update: Context menu items are moved to an upper position
    Fix: Unlimited Section Nesting compatibility issue with Elementor

**Comment by obiPlabon** [comment]
Fixed
