### ISSUE TITLE
Copy / Paste widget

### ISSUE THREAD

**Issue by netgain** [weDevsOfficial/happy-elementor-addons#18]
For pasting into a site, will it ever be possible to copy from an Elementor site that you are not even logged into?

**Comment by sw0rking** [comment]
1.3.0

Release Date – Dec 31, 2019

    New: Promo Box widget
    New: CSS Image Masking (Supported widgets: Card, Info Box, Promo Box, Member, Image, Image Box)
    Update: Cross-Domain Copy Paste UX improved
    Update: Cross-Domain Copy Paste performance improved
    Update: Live Copy Paste UX improved
    Update: Live Copy Paste performance improved
    Update: Context menu items are moved to an upper position
    Fix: Unlimited Section Nesting compatibility issue with Elementor
