### ISSUE TITLE
Gravity Forms widget - multiple issues

### ISSUE THREAD

**Issue by oceandiveloper** [weDevsOfficial/happy-elementor-addons#19]
I'm using your Gravity Forms widget for the first time on a new project and found a couple of issues that I would like to address:

1) the form field padding setting in your widget is not applied in front-end because it's overwritten by Gravity Forms' own CSS (formsmain.min.css).
<img width="1004" alt="Screen Shot 2020-01-02 at 10 53 34" src="https://user-images.githubusercontent.com/43462095/71650916-816b0a00-2d54-11ea-886f-f2c1908bac7d.png">

2) What are the "Sub label" settings under “Form Fields Label” for? the field description? If I change the settings for “Sub label margin” and “Sub label typography” nothing happens for me. Therefore I have to go back to CSS to change the field description styles.

3) Section break title typography - letter-spacing setting doesn’t change anything

4) Page break “next” and “previous” buttons - no options to change typography or padding

**Comment by obiPlabon** [comment]
This issue has been fixed
