### ISSUE TITLE
Step Flow - Some icons aren't loading

### ISSUE THREAD

**Issue by Pagonz342** [weDevsOfficial/happy-elementor-addons#2]
Hi There,

I'm using the step flow and certain icons aren't loading on the preview mode.

The icons shows on elementor page builder but they aren't showing on the actually site once I update changes. I cleared cache (browser and server) and still nothing. 

I noticed that certain icons will show and other won't. 

Picture one shows the icons on elementor editor
Picture two don't show the icons on the live page

![SS 1](https://user-images.githubusercontent.com/54489062/63644636-656aa400-c6a2-11e9-84dd-53baca44250d.png)
![SS 2 - live page](https://user-images.githubusercontent.com/54489062/63644637-656aa400-c6a2-11e9-8429-863a1578fce1.png)

Thoughts?

Thanks,

Paul G

**Comment by thebengalboy** [comment]
Hello @Pagonz342 

Can you please name the icons that are not working? We have checked 10-15 icons randomly and all seems okay so far. I can see you have used the truck icon, I have tried with that but seems okay to me. Reference screenshot: https://prnt.sc/ox8euf

However, which theme you are using? Have you tried changing the theme? Sometimes, theme can cause such kind of problems.

Let us know the update :)

Thanks

**Comment by Pagonz342** [comment]
Hi there,

I'm using Astra 2.0 theme. I will try to change themes and report in a bit.

Thanks,

Paul G

**Comment by Pagonz342** [comment]
Hi there,

I changed to 2017 theme and it still not working. 

I use WP Rocket. Do you think the following settings have anything to do with it as well?
![wp rocket](https://user-images.githubusercontent.com/54489062/63653013-24af7100-c71c-11e9-8ad7-2811916e2ccd.png)

**Comment by Pagonz342** [comment]
Hi there again,

I deactivate all the plugins but elementor and happy addons and still doesn't show =/

I'm wondering what could it be.

Best,

Paul G

**Comment by thebengalboy** [comment]
Hello @Pagonz342 

Minifying JS/CSS can cause such kind of problem but if you have deactivated all of the other plugins, it should work. I'm not sure what is happening on your site without checking it.

However, I'd request you to contact our support center further. You can email to support@wedevs.com; We'll have a look at it.

Thanks

**Comment by obiPlabon** [comment]
Hi @Pagonz342 

All the icons control have been updated including the Step Flow to the latest icon manager, now on all the icons will work perfectly. Also, Step Flow arrow alignment issue has been resolved. So, please update your existing Happy Elementor Addons to **1.5.0** and enjoy a smooth experience.

We are closing the issue.

Thanks
