### ISSUE TITLE
Happy Addons enabled stops Rank Math working in Elementor

### ISSUE THREAD

**Issue by siddallj** [weDevsOfficial/happy-elementor-addons#24]
<img width="272" alt="Screenshot 2020-02-12 at 16 07 22" src="https://user-images.githubusercontent.com/10632889/74353400-c5204d00-4db1-11ea-9402-fbfa11b9b483.png">
When Happy Addons is enabled the Rank Math option no longer works in Elementor Pro, it just shows 
Search widget
Soon as I disable Happy Addons the Rank Math option is fully functioning

Ive disabled all plugins, the issue is only there when Happy Addons is enabled
Theme is Hello

All plugins are using the latest versions

**Comment by obiPlabon** [comment]
This issue has been resolved in version `2.6.1`

Here's the changelog -
https://wordpress.org/plugins/happy-elementor-addons/#developers
