### ISSUE TITLE
Happy Addons stopping typing in Elementor Heading widget

### ISSUE THREAD

**Issue by paulherzlich** [weDevsOfficial/happy-elementor-addons#25]
With the latest versions of Happy Addons and Elementor and Elementor Pro:

1. Drag on a heading widget
2. Type something into the widget on the panel, replacing the default 'Add Your Heading Text Here'; it shows up on the workspace
3. Amend the text in the workspace - it does not get updated back on the panel

or

1. Drag on a heading widget
2. Type something into the widget on the workspace; it does not get updated back on the panel

there are many permutations of this including ones where you can't update the widget text in either place.

<img width="1266" alt="Screenshot 2020-02-15 at 17 17 27" src="https://user-images.githubusercontent.com/7724692/74591295-12e9bf00-5017-11ea-83e1-91e172f0931c.png">

**Comment by obiPlabon** [comment]
This issue has been resolved in version `2.6.1`

Here's the changelog -
https://wordpress.org/plugins/happy-elementor-addons/#developers
