### ISSUE TITLE
Happy add-on pro for wordpress

### ISSUE THREAD

**Issue by MayPee** [weDevsOfficial/happy-elementor-addons#28]
![Inkedscreencapture4_LI](https://user-images.githubusercontent.com/58028386/77227024-7a9aa900-6b85-11ea-94ab-a38127be4fe0.jpg)
![Inkedscreencapture6_LI](https://user-images.githubusercontent.com/58028386/77227036-92722d00-6b85-11ea-80e4-35be2b498557.jpg)

Hi. Can you please help me. I have purchased the pro version of happy add-ons but can't paste the add-on to the page i'm building. I have tried about everything. Not sure if it's a browser problem or the elementor version. I've watched the recommended videos but seems like the past site on my page is not the same. I'm using elementor 2.9.6. And in the vids, seems like a different version being used. Check the attached files where live copy is situated:

**Comment by obiPlabon** [comment]
We made some UX improvements, hence the placement is different. Otherwise, the functionality is the same.
