### ISSUE TITLE
Card widget html issues

### ISSUE THREAD

**Issue by bbordic** [weDevsOfficial/happy-elementor-addons#3]
Hello, I'm using the card widget and trying to add some html tags to the description under the Title/Description section and the html works when previewing it within elementor but not when viewing the page when it's published. Any ideas? Thanks,

**Comment by thebengalboy** [comment]
Hello @bbordic 

May I know the specific tags you used? I have just checked with the <a> tag which seems working fine here. Reference screenshot: https://prnt.sc/oy1bg0

Regards,

**Comment by obiPlabon** [comment]
All the widgets now support some specific HTML tags and it's mentioned in field description.
