### ISSUE TITLE
Template dropdown items barely visible

### ISSUE THREAD

**Issue by alpinevp** [weDevsOfficial/happy-elementor-addons#44]
<img width="613" alt="Screen Shot 2020-06-09 at 7 57 19 AM" src="https://user-images.githubusercontent.com/16783650/84164346-42d62b80-aa27-11ea-8d5d-069d5d2a9094.png">

You might want to change the template dropdown list to black so they are more visible, grey on white, #f1f3f5, is not really an intelligent or user friendly move.

**Comment by obiPlabon** [comment]
Hello @alpinevp 

You'll be happy to hear that it's been fixed in version `2.12.2` on 10 June 2020
https://wordpress.org/plugins/happy-elementor-addons/#developers

Thank you :)
