### ISSUE TITLE
Not redering propery

### ISSUE THREAD

**Issue by sojungyou** [weDevsOfficial/happy-elementor-addons#49]
how can i fix this

wordpress editor
![](https://i.gyazo.com/70505b9f76742f727dd08d4f74638bca.png)

my domain 
![](https://i.gyazo.com/98c9a55ad2396ef62abfb7c798fc1fec.png)

thank you

**Comment by matgott** [comment]
I'm having same issue. In Elementor editor all works fine but the site doesn't work well. Console log "elementorModules.frontend is undefined"

**Comment by obiPlabon** [comment]
Hello, @everyone we are really sorry for the inconvenience and trouble you went through. And the good news is we have released v2.14.2 with all the JS and editor related fixes. Please update your HappyAddons asap to the latest version.

Details: https://wordpress.org/plugins/happy-elementor-addons/#developers

Thank you
