### ISSUE TITLE
Internal server error on using happy elements multiple widgets in same page

### ISSUE THREAD

**Issue by ashishpanda330** [weDevsOfficial/happy-elementor-addons#5]
The plugin shows internal server error when loading elementor the next time after creating a page with multiple happyaddons widget and closing the page. If you can help me with the issue than it could be a great help. Note that these errors don't appear when using a single widget or advance options.
![Screenshot (3)](https://user-images.githubusercontent.com/41537853/65384817-85928f00-dd44-11e9-9e1c-67c7ff78367f.png)
I have submitted the screenshot.
You can contact me at ashishpanda330@gmail.com

**Comment by obiPlabon** [comment]
@ashishpanda330 Thanks for reporting the issue. We need more information on this to figure out the issue as well as the solution. Please check your email, thanks.

**Comment by ashishpanda330** [comment]
It's pleasure using your plugin and will be happy to help you out.
Please help me to solve this issue as soon as possible as it's breaking my
client's site.
What kind of more info are you looking for?
