### ISSUE TITLE
Provide or Document Hooks, Actions, and Filters

### ISSUE THREAD

**Issue by heyfletch** [weDevsOfficial/happy-elementor-addons#51]
Happy Addons adds a LOT of features, some of which I do not want on my site or my clients' sites. Please provide a way to remove some of these features. For example, using a WordPress hook to deactivate.

For example, if I want to remove a widget from the site, I just untick the box. But for features like Happy Clone, Cross-Domain Copy Paste, etc., there is no interface to disable. So, please provide a simple filter function we can use to deactivate.

Also, please document somewhere which filters are available to developers to hook into Happy Addons.

**Comment by mmarj** [comment]
Hello @heyfletch 

You would be glad to know that today we released 2.13.0 with several filters/hooks. Please know the details [from here](https://github.com/weDevsOfficial/happy-elementor-addons/wiki/Hooks). Note, this filter will be effective from this version 2.13.0 not with the older version.

Thanks & regards.

**Comment by heyfletch** [comment]
Yes, this is awesome! Thank you so much. I will start using these, and hopefully you'll add new hooks, such as disabling Happy Icons, Live Copy, etc. But yes, this is exactly what I was looking for... bravo!
