### ISSUE TITLE
CSS Transform Effects not working in the front end

### ISSUE THREAD

**Issue by Creatorzz1** [weDevsOfficial/happy-elementor-addons#53]
**Describe the bug**
Editor mode the CSS Transform Rotate works. Once reloaded and in the frontend, it will not rotate whatsoever. 

**Expected behavior**
Be tilted properly.

**Desktop**
- Browser: viewable on Chrome, Safari, etc.
 - Elementor Version: PRO 2.10.3, Regular Elementor 2.9.14
 - HappyAddons Version 2.13.0

No other plugins added at all. Tried cache clearing. Tried changing the size of the viewport and everything else. Other CSS transforms also do not work in the front end. The first video shows how it looks frontend/live (wrong), the next video shows it right in the editor mode.

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/69211726/89322919-fab43d80-d652-11ea-94a0-307e3fafeb92.gif)

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/69211726/89322913-f720b680-d652-11ea-927e-4d576e60ac65.gif)

**Comment by NF1984** [comment]
I'm having the same issue with 'skew'. I noticed that the 'hover' option is there now, I don't think it used to be. So I had to match all my on hover settings to the normal settings to make it look right in the elementor editor, but on the front end there is no skewing at all.

**Comment by motiur-designer** [comment]
I have also the same problem. css transform (Rotate Z) not working

**Comment by obiPlabon** [comment]
Hello, @everyone we are really sorry for the inconvenience and trouble you went through. And the good news is we have released v2.14.2 with all the JS and editor related fixes. Please update your HappyAddons asap to the latest version.

Details: https://wordpress.org/plugins/happy-elementor-addons/#developers

Thank you
