### ISSUE TITLE
Firefox rendering problems

### ISSUE THREAD

**Issue by matgott** [weDevsOfficial/happy-elementor-addons#60]
**Describe the bug**
Plugin works fine in edition mode but in frontend site rendering is wrong and console throw some errors like:
`Uncaught TypeError: can't access property "Document", elementorModules.frontend is undefined
    <anonymous> https://tecnobaterias.com.ar/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.2:2
    n https://tecnobaterias.com.ar/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.2:2
    <anonymous> https://tecnobaterias.com.ar/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.2:2
    n https://tecnobaterias.com.ar/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.2:2
    <anonymous> https://tecnobaterias.com.ar/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.2:2
    n https://tecnobaterias.com.ar/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.2:2
    <anonymous> https://tecnobaterias.com.ar/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.2:2
    <anonymous> https://tecnobaterias.com.ar/wp-content/plugins/elementor-pro/assets/js/frontend.min.js?ver=3.0.2:2`

Editor: https://ibb.co/CQpd2v2
Website: https://ibb.co/3ykxGkJ

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Elementor Version: 3.0.6
 - HappyAddons Version: 2.14.1

**Additional context**
I trying removing all other plugins, but the problem persist. In chrome works well, my problem is in Firefox.

**Comment by johnbolandwp** [comment]
I'm also having this problem.

**Comment by PaulinHalenria** [comment]
So do I... would be nice is someone could take this in charge

**Comment by obiPlabon** [comment]
Hello, @everyone we are really sorry for the inconvenience and trouble you went through. And the good news is we have released `v2.14.2` with all the JS and editor related fixes. Please update your HappyAddons asap to the latest version.

Details: https://wordpress.org/plugins/happy-elementor-addons/#developers

Thank you
