### ISSUE TITLE
The newest update throws JS errors

### ISSUE THREAD

**Issue by hyperjit** [weDevsOfficial/happy-elementor-addons#61]
The **2.14.1** update is causing Elementor's sticky effects to not work. Checked the console, it shows some JS errors (attached picture for reference).

![20200908-052912-chrome](https://user-images.githubusercontent.com/70923727/92421534-98d97d00-f196-11ea-9823-bf859952c93c.png)

Rolling back to **2.14.0** solves it.

**To Reproduce**
1. Update to HappyAddons 2.14.1 from WP Dashboard
2. Check the sticky elements set in Elementor in the frontend
3. Check console in Chrome and reload the page

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox & Edge
 - Elementor Version: 3.0.6.
 - HappyAddons Version: 2.14.1
 - Other 3rd party addons: Elementor Pro, Litespeed Cache, Advanced Custom Fields

**Comment by imbrick** [comment]
Getting the same problem here since the last update.

**Comment by hyperjit** [comment]
> Getting the same problem here since the last update, blocking the popup display.

Rollback to 2.14.0. That is a temporary workaround for now. Looks like the team is pretty inactive here too. Mailed them, no response yet.

**Comment by formulaclick** [comment]
Same problem here in all my websites. Please fix this!

**Comment by isaline79** [comment]
Same problem with my website since the update to 2.14.1

**Comment by Abbasi007** [comment]
facing the same issue. Please fix this as soon as possible.

**Comment by asanger** [comment]
Also seeing this error

**Comment by asanger** [comment]
Where can I find version 2.14.0? All the links have been updated to 2.14.1.

**Comment by formulaclick** [comment]
1 week and no solutions for this issue. At least this helps me to decide whether I renew developer license or not

**Comment by HeinrichMarketing** [comment]
Same here... why is nobody responding?

**Comment by navaweb** [comment]
same, and it's causing Elementor link to not be visible in Admin bar ... and causing all pages while in Edit mode (not Elementor edit mode, but just Page > Edit mode) to have missing images, wrong formatting etc...

Uncaught TypeError: Cannot read property 'Document' of undefined
    at Object.<anonymous> (frontend.min.js:2)
    at n (frontend.min.js:2)
    at Object.<anonymous> (frontend.min.js:2)
    at n (frontend.min.js:2)
    at Object.<anonymous> (frontend.min.js:2)
    at n (frontend.min.js:2)
    at frontend.min.js:2
    at frontend.min.js:2
happy-addons.min.js:1 Uncaught TypeError: Cannot read property 'handlers' of undefined
    at happy-addons.min.js:1
    at dispatch (jquery.js:3)
    at r.handle (jquery.js:3)
    at Object.trigger (jquery.js:3)
    at jquery.js:3
    at Function.each (jquery.js:2)
    at n.fn.init.each (jquery.js:2)
    at n.fn.init.trigger (jquery.js:3)
    at Frontend.init (frontend.min.js:2)
    at HTMLDocument.<anonymous> (frontend.min.js:2)


please fix! this was reported 9 days ago? :-o

**Comment by steveavador** [comment]
Same problem! and is causing other plugins to have problems as well.

**Comment by hyperjit** [comment]
Looks like they released an update with the fixes.
![image](https://user-images.githubusercontent.com/70923727/93736933-6badb580-fbff-11ea-92cd-b76ac53eada0.png)

**Comment by obiPlabon** [comment]
Hello, @everyone we are really sorry for the inconvenience and trouble you went through. And the good news is we have released `v2.14.2` with all the JS and editor related fixes. Please update your HappyAddons asap to the latest version.

Details: https://wordpress.org/plugins/happy-elementor-addons/#developers

Thank you
