### ISSUE TITLE
Elementor custom template with happyaddon widget not appearing on published page

### ISSUE THREAD

**Issue by MarinosDakis** [weDevsOfficial/happy-elementor-addons#63]
**Describe the bug**

Hello,

I have been losing my mind for the past few hours...

The following issue is that I have used the Team Member widget in an Elementor custom template and after importing the template that contains the happyaddon widget, it does not show on the published page.

I have tried other widgets such as the normal Elementor title, and the default Team member widget as shown in the screenshots and those appear without an issue.

If you have any insight that would be amazing.
Thank you!.

**Expected behavior**
The template should show on a published page

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/54782000/93009279-f2ea9180-f54c-11ea-9bfe-3002c4c65c88.png)
![screenshot2](https://user-images.githubusercontent.com/54782000/93009280-f3832800-f54c-11ea-8fe9-bfe3cf108ee5.png)
![screenshot3](https://user-images.githubusercontent.com/54782000/93009281-f41bbe80-f54c-11ea-97b8-323a23d7a49e.png)
![screenshot4](https://user-images.githubusercontent.com/54782000/93009282-f4b45500-f54c-11ea-8626-a44e6012d4ca.png)

**Desktop**
 - OS: Windows
 - Google chrome
 - Elementor Version: 3.0.7 
 - HappyAddons Version: 2.14.1
 - Elementor Pro Version: 3.0.4

**Comment by PaulMyDigipal** [comment]
Same issue here and Elementor support has confirmed the issue came from Happy Elementor... please let me know if you find a solution thanks!

**Comment by obiPlabon** [comment]
Hello @MarinosDakis sorry for the inconvenience. We couldn't recreate the issue in our test server, so it'd be really helpful for both of us if you send us an email at support@weDevs.com with your site and access details. So that we can check and figure out a better solution.

Thanks
