### ISSUE TITLE
issue with cards and icon box

### ISSUE THREAD

**Issue by roy625** [weDevsOfficial/happy-elementor-addons#64]
**Describe the bug**
the svg when uploaded they aren't visible in the edit box option 

and in the edit mode every thing seems right but as soon as i view it on live website it is all jumbled
![Screenshot (6)](https://user-images.githubusercontent.com/60127308/93022648-03137700-f608-11ea-983b-e3feea5fc314.png)
![Screenshot (4)](https://user-images.githubusercontent.com/60127308/93022649-04dd3a80-f608-11ea-9c82-fab32109185e.png)
![Screenshot (5)](https://user-images.githubusercontent.com/60127308/93022652-0870c180-f608-11ea-95c1-81ceedfcb851.png)
![Screenshot (6)](https://user-images.githubusercontent.com/60127308/93022653-0a3a8500-f608-11ea-8258-fa5b959f20c0.png)

**Comment by obiPlabon** [comment]
Hello @roy625 sorry for the inconvenience. It seems your site has mixed content issue, that means some assets (css,js,img) are loading using https and some are http. Could you please check your browser console and confirm us or share a test page with HappyAddons widget?

Thanks

**Comment by roy625** [comment]
I have Solved thaat issue from My side
