### ISSUE TITLE
Css transform and fade in animation

### ISSUE THREAD

**Issue by AndersJpg** [weDevsOfficial/happy-elementor-addons#65]
https://dl.dropboxusercontent.com/s/9rt4alrztdrvyb1/qvh46X634u.mp4
when an image ex has CSS translate on and then using a fade-in animation as seen on the video, it breaks at the end, does not follow the new path you giving the item.

**Comment by obiPlabon** [comment]
Thank you for the feature request, forwarding this to our development team.
