### ISSUE TITLE
Elementor not visible

### ISSUE THREAD

**Issue by mmmsss211** [weDevsOfficial/happy-elementor-addons#66]
**Describe the bug**
Elementor just updated recently and all the previous work Became invisible. I had to deactivate each plugin and found that happy addons were the problem. 

You can see the designs when inside the elementor editor but everything goes blank when on the actual site.

**To Reproduce**
1. Design a new elementor page
2. Install and activate happy addons

**Comment by navaweb** [comment]
I have the same issue... but the page isn't blank, it is just totally messed up, and Elementor link in the admin bar is gone ...

**Comment by PaulMyDigipal** [comment]
Same issue here and Elementor support has confirmed the issue came from Happy Elementor... please let me know if you find a solution thanks!

**Comment by obiPlabon** [comment]
Hello, @mmmsss211 @navaweb @PaulMyDigipal we are sorry for the inconvenience. We have released the `v2.14.2` update with the necessary fixing on 20 September 2020, please update your HappyAddons to the latest version. https://wordpress.org/plugins/happy-elementor-addons/#developers

Thank you

**Comment by PaulMyDigipal** [comment]
Hi there,
Thanks a lot for letting us know about this update.
I've been given a link to install the version 2.14.3, should i keep this
one instead of installing the one you've just sent (2.14.2)?
Thanks,

Paul André
+44 740 2230 833
paul.and.itc@gmail.com

**Comment by obiPlabon** [comment]
@PaulMyDigipal I guess you were given an internal release version. Please use the link I shared it's public and updated.

Thanks

**Comment by PaulMyDigipal** [comment]
Just installed it and looks like it's doing a perfect job!
Congrats guys your plugin is fantastic.
Keep up the good work!
Kind regards,

Paul André
+44 740 2230 833
paul.and.itc@gmail.com

**Comment by obiPlabon** [comment]
Thank you @PaulMyDigipal
