### ISSUE TITLE
Weird image size handling with card widget

### ISSUE THREAD

**Issue by zahnd** [weDevsOfficial/happy-elementor-addons#70]
Hi

From my experience, how the image size is handled with the card widget, is not dynamic enough. Only being able to set a static value for height doesn't work at all regarding responsiveness. The following video explains what I mean: https://monosnap.com/file/CMM3DboVJSFA8ePYcYUhe32IinK1PV

My suggestion would be to add a percentage value for the height of the image or/and an option to set the image size to contain or cover in combination with different image positions like "center, center", "bottom, center", "top, left" etc.

Thank you and kind regards, Stefan

**Comment by obiPlabon** [comment]
Hi @zahnd thank you for reporting the issue and sorry for the inconvenience.

We'll update the image sizing option as per your suggestion in the next update.

Thanks
