### ISSUE TITLE
copy / paste

### ISSUE THREAD

**Issue by file4free** [weDevsOfficial/happy-elementor-addons#72]
Hello, copy / paste not working at all...can you help?

**Comment by obiPlabon** [comment]
@file4free can you please explain in detail?

**Comment by file4free** [comment]
Yes, unfortunately the copy paste function and the live copy paste are NOT working for me at all, Astra theme Elementor Pro. Everything is updated. 

-------- הודעה מקורית --------מאת: Md Obidullah <notifications@github.com> תאריך: 29.10.2020  20:34  (GMT+02:00) אל: weDevsOfficial/happy-elementor-addons <happy-elementor-addons@noreply.github.com> עותק: file4free <file4free@gmail.com>, Mention <mention@noreply.github.com> נושא: Re: [weDevsOfficial/happy-elementor-addons] copy / paste (#72) 
@file4free can you please explain in detail?

**Comment by obiPlabon** [comment]
@file4free can you please drop us an email at support@wedevs.com with your site URL and a test account. We need to experience the issue the figure out the problem and solution.

Thanks
