### ISSUE TITLE
WPForms lite only styling

### ISSUE THREAD

**Issue by Klimkowski** [weDevsOfficial/happy-elementor-addons#8]
Hi guys, when I try to style WPForms (Full version) I'm presentend with the following:

> Hi, it seems WPForms is missing in your site. Please install and activate WPForms first.

**Comment by thebengalboy** [comment]
Hello @Klimkowski 

We have already fixed the issue and hoping to release it with the upcoming version. Thanks for noticing and letting us know. We really appreciate your cooperation :)

Regards,
