### ISSUE TITLE
Unable to exit elementor - missing menu

### ISSUE THREAD

**Issue by tissi-2** [weDevsOfficial/happy-elementor-addons#83]
When clicking on the elementor hamburger icon in the left upper corner you will get a menu in which you can choose the last option to exit elementor. This menu won't show up if happy addons is activated.

When deactivating happy addons the elementor menu is showing up again.

 - OS: Win10 x64 version 2004
 - Browser Firefox 83.0 64bit
 - Elementor Version 3.0.14
 - HappyAddons Version 2.16.0
 - Elementor Pro 3.0.8

**Comment by blivesay77** [comment]
I am having the same issue as of yesterday
![Screen Shot 2020-12-10 at 8 46 15 AM](https://user-images.githubusercontent.com/75793168/101780218-3f9a2600-3ac4-11eb-813b-ca8bf48a7ba4.png)
![Screen Shot 2020-12-10 at 8 45 46 AM](https://user-images.githubusercontent.com/75793168/101780224-40cb5300-3ac4-11eb-8391-2dc2139ac64c.png)

**Comment by yewzy** [comment]
I am also having the same issue.

From console:
`Uncaught TypeError: Cannot read property 'urls' of undefined
    at Function.m.initGroups (editor.min.js?ver=3.0.14:2)
    at Function.m.getGroups (editor.min.js?ver=3.0.14:2)
    at Function.m.addItem (editor.min.js?ver=3.0.14:2)
    at editor.min.js?ver=2.16.0:1
    at editor.min.js?ver=2.16.0:1
m.initGroups @ editor.min.js?ver=3.0.14:2
m.getGroups @ editor.min.js?ver=3.0.14:2
m.addItem @ editor.min.js?ver=3.0.14:2
(anonymous) @ editor.min.js?ver=2.16.0:1
(anonymous) @ editor.min.js?ver=2.16.0:1
template-library.min.js?ver=2.16.0:1 Uncaught TypeError: i.translate is not a function
    at template-library.min.js?ver=2.16.0:1
    at template-library.min.js?ver=2.16.0:1
(anonymous) @ template-library.min.js?ver=2.16.0:1
(anonymous) @ template-library.min.js?ver=2.16.0:1
`

**Comment by blivesay77** [comment]
The latest update seemed to fix this issue. Just updated it and it works.

**Comment by yewzy** [comment]
Thanks for the heads up @blivesay77 !

**Comment by hasinhayder** [comment]
We're really sorry for the inconvenience. Please update the free version of Happy Addons that has been released last night. This will fix this issue.
