### ISSUE TITLE
WP plugin update count wrong after Pro activation

### ISSUE THREAD

**Issue by paulherzlich** [weDevsOfficial/happy-elementor-addons#9]
Start with WP needing no updates. Install and activate Pro plugin and activate the Pro licence. WP now shows a count of 1 update needed. But the list of plugins is not showing any updates needed. You need to deactivate then reactivate the Pro plugin to get rid of the spurious plugin update count.

After Pro Licence activation
![Screenshot 2019-11-04 at 10 16 22](https://user-images.githubusercontent.com/7724692/68110785-ec7f9800-feed-11e9-9512-ca1c61a2d959.png)
After deactivating and re-activating Pro plugin
![Screenshot 2019-11-04 at 10 16 41](https://user-images.githubusercontent.com/7724692/68110860-120ca180-feee-11e9-85a4-5adb00edfb3f.png)

**Comment by obiPlabon** [comment]
Hello @paulherzlich 
There was a problem with the auto-updater initialization and we have fixed that in version 1.0.2. Please update to the latest version. You can download the latest version from your account on happyaddons.com 

Thanks
